### ISSUE TITLE
Error starting server... cannot find module '../build/app'

### ISSUE THREAD

**Issue by donwalrus** [learningcom/elastalert-ui#3]
When I run 'npm start' from the "server" directory after following instructions (non-Docker), I keep getting this error:

```
> server@0.0.0 start /home/me/elastalert-ui/server
> node ./bin/www

module.js:472
    throw err;
    ^

Error: Cannot find module '../build/app'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/me/elastalert-ui/server/bin/www:7:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
Additional output:

```
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! server@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the server@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/me/elastalert-ui/server/npm-debug.log
```

I was unable to get the docker image working so I did the non-docker route. I'm able to get the client running on port 4200, but not the server due to the missing "build" dir/module

**Comment by iamambrus** [comment]
get a possibly related error in the server (using Docker):

"Error: Not Found\n    at /opt/app/server/build/app.js:25:15\n    at Layer.handle [as handle_request] (/opt/app/server/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/opt/app/server/node_modules/express/lib/router/index.js:312:13)\n    at /opt/app/server/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/opt/app/server/node_modules/express/lib/router/index.js:330:12)\n    at next (/opt/app/server/node_modules/express/lib/router/index.js:271:10)\n    at host.middleware (/opt/app/server/node_modules/jsend/index.js:139:3)\n    at Layer.handle [as handle_request] (/opt/app/server/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/opt/app/server/node_modules/express/lib/router/index.js:312:13)\n    at /opt/app/server/node_modules/express/lib/router/index.js:280:7"

**Comment by steelheaddigital** [comment]
Sorry it took me a while to get to this. I've made a few fixes and updated the readme with a few missing steps. Let me know if you can get it running with these changes. Thanks
